### ISSUE TITLE
Scope status widget (sidebar) – CSS issue

### ISSUE THREAD

**Issue by bezludny** [formaweb/formadmin#14]
<img width="336" alt="screen shot 2017-09-20 at 10 38 20 pm" src="https://user-images.githubusercontent.com/3892006/30664110-47fccef6-9e55-11e7-9220-2d423267c565.png">

The widget appears when we use scopes for index page:
<img width="736" alt="screen shot 2017-09-20 at 10 42 23 pm" src="https://user-images.githubusercontent.com/3892006/30664095-37cf48ba-9e55-11e7-9f38-0c8d6e03a068.png">

Original AA widget:
<img width="332" alt="screen shot 2017-09-20 at 10 40 20 pm" src="https://user-images.githubusercontent.com/3892006/30663875-bc9e684c-9e54-11e7-9a9a-4c423acc9845.png">

P. S. Thanks for your GREAT job! I love your theme!

**Comment by bezludny** [comment]
#15 tested locally. Looks like it is:

```scss
:not(#search-status-_sidebar_section) {
      .panel_contents {
        padding: 0;

        > div {
          padding: 15px;
        }
      }
    }
```
