### ISSUE TITLE
Sub-Menu items bleed out of container.

### ISSUE THREAD

**Issue by abrambailey** [formaweb/formadmin#8]
![image](https://cloud.githubusercontent.com/assets/978462/23759547/b5c485ce-04b2-11e7-8465-d2d2d2b25eff.png)

**Comment by abrambailey** [comment]
This fixed it for me:

```css
#header.header .header-item ul {
  width: auto;
  max-width: none;
}
```
