### ISSUE TITLE
Can't adjust width of columns

### ISSUE THREAD

**Issue by abrambailey** [formaweb/formadmin#9]
![image](https://cloud.githubusercontent.com/assets/978462/23760904/bdaf6a3e-04b6-11e7-9c15-4411b521cb19.png)

I tried setting the following:
```css
.resource_selection_toggle_cell, .resource_selection_cell {
  width: 0
}
```
However, I still cannot remove all the space on the left column or right column.

**Comment by caiotarifa** [comment]
You'll need to set a fixed size on `td`, not on the `div`.

Try something like:

```css
.col-selectable {
  width: 70px;
}
```

**Comment by abrambailey** [comment]
Oh sorry, I had tried that as well. In fact doing something like this does not work:
```css
.col-selectable, .resource_selection_toggle_cell, .resource_selection_cell {
  width: 50px;
}
```
I find the issue only crops up when there are a smaller number of columns with thin content. There is no issue when lots of columns exist. Try setting up a 3 column table with selection and actions and not much content in the middle column.

**Comment by caiotarifa** [comment]
And then...?

```css
.col {
  width: 100%;
}

.col-selectable {
  width: 70px;
}
```

I tried here and it worked like a charm!

**Comment by abrambailey** [comment]
That created a weird issue for me with tables with more columns (the first column after selectable was too big and the others too small) ... but I just removed the other CSS and somehow this is working for me now on both types of tables!
```css
.col-selectable {
  width: 70px;
}

.col-actions {
  width:100px;
}
```
![image](https://cloud.githubusercontent.com/assets/978462/23763841/e00cbafa-04c0-11e7-869d-5b14aaced743.png)
